# Use root/example as user/password credentials
version: "3.8"

services:
  app:
    build: .
    ports:
      - "1323:1323"
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/gooal?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
