// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Drag_n_Drop() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>Build your questionnaire</h1><div class=\"grid\"><aside class=\"left\"><form class=\"sortable\" hx-post=\"/items\" hx-trigger=\"end\"><div class=\"htmx-indicator\">Updating...</div><div><input type=\"hidden\" name=\"item\" value=\"1\">Text Input</div><div><input type=\"hidden\" name=\"item\" value=\"2\">Number Input</div><div><input type=\"hidden\" name=\"item\" value=\"3\">Range</div><div><input type=\"hidden\" name=\"item\" value=\"4\">Select Input</div><div><input type=\"hidden\" name=\"item\" value=\"5\">Radio Button</div></form></aside><main class=\"right sortable\"></main></div><style>\n    .grid{\n        display: grid;\n        grid-template-columns: repeat(2, 1fr);\n        gap: 2rem;\n    }\n\n    main{\n        border: 2px solid red;\n    }\n\n\n    aside{\n        border: 1px solid blue;\n    }\n\n    </style><script>\n        document.addEventListener(\"DOMContentLoaded\", function() {\n            var leftSortable = new Sortable(document.querySelector(\".left .sortable\"), {\n                group: {\n                    name: \"shared\",\n                    pull: \"clone\",\n                    put: false\n                },\n                animation: 150,\n                ghostClass: 'blue-background-class'\n            });\n\n            var rightSortable = new Sortable(document.querySelector(\".right\"), {\n                group: {\n                    name: \"shared\",\n                    pull: false,\n                    put: true\n                },\n                animation: 150,\n                ghostClass: 'blue-background-class',\n                onAdd: function(evt) {\n                    var itemEl = evt.item;\n                    var clonedEl = itemEl.cloneNode(true);\n                    evt.item.parentNode.replaceChild(clonedEl, evt.item);\n                }\n            });\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
